name: data
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.8.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - keras-preprocessing=1.1.2
  - krb5=1.19.4
  - lerc=3.0
  - libclang13=14.0.6
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.5.4
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - docopt==0.6.2
      - flatbuffers==23.3.3
      - gast==0.4.0
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.53.0
      - h5py==3.8.0
      - jax==0.4.8
      - joblib==1.2.0
      - keras==2.12.0
      - liac-arff==2.5.0
      - libclang==16.0.0
      - markdown==3.4.3
      - ml-dtypes==0.1.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pipreqs==0.4.11
      - protobuf==4.22.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.1
      - sklearn==0.0.post1
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.12.0
      - tensorflow-macos==2.12.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - werkzeug==2.2.3
      - wrapt==1.14.1
      - yarg==0.1.9
prefix: /Users/xiezherui/miniconda3/envs/data
